name: rng_gozco
# on: [push]
on:
  workflow_dispatch:
      
jobs:
  pn:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        go: [1.1, 10]
        flag: [A, B]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: S o ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Spv
      uses: actions/checkout@v1
    - name: rr_go
      run: |
        sudo apt update -y && sleep 7
        
  win-1:
    needs: pn
    runs-on: windows-latest
    strategy:
      max-parallel: 256
      fail-fast: false
      matrix:
         go: [1.1, 1.d2, 1.1c3, 1.1c4, 1.1q5, 1.16o, 1.17s, 1.18s, 1.1w9]
         flag: [kmn, oiu, qcwe, nvb, lpd, scds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]  
    timeout-minutes: 355
    env:
        NUM_JOBS: 256
        JOB: ${{ matrix.go }}
    steps:
    - name: stg2o ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Stg3
      uses: actions/checkout@v1
    - name: finish
      run: |
        pip install selenium
        pip install names
        pip3 install selenium
        python3 dumc.py   
